#pragma once

/* IMPORTANT: This file is autogenerated from Hooks Generator Tool */
/* Note: If you want to add an include please add it in `hooks_template.cpp` and then run the generator tool */

#include <Windows.h>

/* Logging */
#define Log(...) {  \
    logger.write(__VA_ARGS__); \
}

/*****************************************************************************/
/*                                   HOOKS                                   */
/*****************************************************************************/



static HANDLE (*True_CreateFileA) (
    LPCSTR lpFileName, 
    DWORD dwDesiredAccess, 
    DWORD dwShareMode, 
    LPSECURITY_ATTRIBUTES lpSecurityAttributes, 
    DWORD dwCreationDisposition, 
    DWORD dwFlagsAndAttributes, 
    HANDLE hTemplateFile
    ) = CreateFileA;

static HANDLE Hook_CreateFileA(
    LPCSTR lpFileName, 
    DWORD dwDesiredAccess, 
    DWORD dwShareMode, 
    LPSECURITY_ATTRIBUTES lpSecurityAttributes, 
    DWORD dwCreationDisposition, 
    DWORD dwFlagsAndAttributes, 
    HANDLE hTemplateFile
) {
    Log("{{ 'HookedFunction': 'CreateFileA', 'Parameters': {{ 'lpFileName': '{}', 'dwDesiredAccess': '{}', 'dwShareMode': '{}', 'dwCreationDisposition': '{}', 'dwFlagsAndAttributes': '{}', 'hTemplateFile': '{}'}} }}",
         lpFileName, dwDesiredAccess, dwShareMode, dwCreationDisposition, dwFlagsAndAttributes, hTemplateFile
    );

    return True_CreateFileA(lpFileName, dwDesiredAccess, dwShareMode, lpSecurityAttributes, dwCreationDisposition, dwFlagsAndAttributes, hTemplateFile);
}


static BOOL (*True_CreateProcessA) (
    LPCSTR lpApplicationName, 
    LPSTR lpCommandLine, 
    LPSECURITY_ATTRIBUTES lpProcessAttributes, 
    LPSECURITY_ATTRIBUTES lpThreadAttributes, 
    BOOL bInheritHandles, 
    DWORD dwCreationFlags, 
    LPVOID lpEnvironment, 
    LPCSTR lpCurrentDirectory, 
    LPSTARTUPINFOA lpStartupInfo, 
    LPPROCESS_INFORMATION lpProcessInformation
    ) = CreateProcessA;

static BOOL Hook_CreateProcessA(
    LPCSTR lpApplicationName, 
    LPSTR lpCommandLine, 
    LPSECURITY_ATTRIBUTES lpProcessAttributes, 
    LPSECURITY_ATTRIBUTES lpThreadAttributes, 
    BOOL bInheritHandles, 
    DWORD dwCreationFlags, 
    LPVOID lpEnvironment, 
    LPCSTR lpCurrentDirectory, 
    LPSTARTUPINFOA lpStartupInfo, 
    LPPROCESS_INFORMATION lpProcessInformation
) {
    Log("{{ 'HookedFunction': 'CreateProcessA', 'Parameters': {{ 'lpApplicationName': '{}', 'lpCommandLine': '{}', 'bInheritHandles': '{}', 'dwCreationFlags': '{}', 'lpEnvironment': '{}', 'lpCurrentDirectory': '{}'}} }}",
         lpApplicationName, lpCommandLine, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory
    );

    return True_CreateProcessA(lpApplicationName, lpCommandLine, lpProcessAttributes, lpThreadAttributes, bInheritHandles, dwCreationFlags, lpEnvironment, lpCurrentDirectory, lpStartupInfo, lpProcessInformation);
}


static void (*True_Sleep) (
    DWORD dwMilliseconds
    ) = Sleep;

static void Hook_Sleep(
    DWORD dwMilliseconds
) {
    Log("{{ 'HookedFunction': 'Sleep', 'Parameters': {{ 'dwMilliseconds': '{}'}} }}",
         dwMilliseconds
    );

    return True_Sleep(dwMilliseconds);
}


/*****************************************************************************/
/*                               DETOUR ATTACH                               */
/*****************************************************************************/

void DetourAttach_AllHooks() {
    
    DetourAttach(&True_CreateFileA, Hook_CreateFileA);
    Log("'Registered `CreateFileA` '");
    
    DetourAttach(&True_CreateProcessA, Hook_CreateProcessA);
    Log("'Registered `CreateProcessA` '");
    
    DetourAttach(&True_Sleep, Hook_Sleep);
    Log("'Registered `Sleep` '");
    
}
